language: R
cache: packages

r_packages:
  - devtools

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/spelling

before_script:
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - travis_wait 20 Rscript -e 'goodpractice::gp()'
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_failure:
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

